buildscript {
    ext {
        creds = {
            username = findProperty("github.user") ?: System.getenv("GITHUB_ACTOR")
            password = findProperty("github.token") ?: System.getenv("GITHUB_TOKEN")
        }
    }
    repositories {
        mavenCentral()
        maven {
            url uri("https://maven.pkg.github.com/trevorism/gradle-release-plugin")
            credentials creds
        }
    }
    dependencies {
        classpath 'com.trevorism:gradle-release-plugin:0.7.0'
    }
}

plugins{
    id("io.micronaut.library") version "5.0.2"
    id "jacoco"
}

apply plugin: "com.trevorism.gradle.release"

repositories {
    mavenCentral()
    maven {
        url uri("https://maven.pkg.github.com/trevorism/secure-utils")
        credentials creds
    }
}

micronaut{
    version = "5.1.0"
    importMicronautPlatform = false
}

dependencies {
    api 'com.trevorism:micronaut-security-utils:3.2.0'

    implementation 'com.trevorism:http-utils:2.3.0'
    implementation 'com.google.code.gson:gson:2.14.0'
    implementation 'io.jsonwebtoken:jjwt-api:0.13.0'
    api 'io.micronaut:micronaut-http:5.1.10'
    api 'jakarta.inject:jakarta.inject-api:2.0.1'
    api 'io.micronaut:micronaut-inject:5.1.10'
    implementation 'org.slf4j:slf4j-api:2.0.18'

    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.13.0'
    runtimeOnly 'io.jsonwebtoken:jjwt-gson:0.13.0'

    annotationProcessor 'io.micronaut:micronaut-inject-java:5.1.10'
    annotationProcessor 'io.micronaut.security:micronaut-security-annotations:5.3.1'
    testAnnotationProcessor 'io.micronaut:micronaut-inject-java:5.1.10'
    testAnnotationProcessor 'io.micronaut.security:micronaut-security-annotations:5.3.1'

    testImplementation(platform("org.junit:junit-bom:6.1.3"))
    testImplementation 'io.micronaut:micronaut-router:5.1.10'
    testImplementation 'org.junit.platform:junit-platform-launcher'
    testImplementation 'org.junit.jupiter:junit-jupiter-api'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine'
    testRuntimeOnly 'io.jsonwebtoken:jjwt-impl:0.13.0'
    testRuntimeOnly 'io.jsonwebtoken:jjwt-gson:0.13.0'
    testRuntimeOnly 'org.slf4j:slf4j-nop:2.0.18'
}

test {
    useJUnitPlatform()
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
}

check.dependsOn "jacocoTestReport"

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(25))
    }
}